						
INSERT INTO dbo.product (NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES ('Chromebook 11 - 3120',100,169.0,'resources/images/product/COMPUTER RELATED/T3.JPG','resources/images/product/COMPUTER RELATED/Chromebook 11 - 3120.JPG','1001');



INSERT INTO dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('INSPIRON SMALL DESKTOP',20,279.0,'resources/images/product/COMPUTER RELATED/T2.JPG','resources/images/product/COMPUTER RELATED/INSPIRON SMALL DESKTOP.JPG','1002');



INSERT INTO dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('Inspiron_11_3000_3168_MultiColor',120,199.0,'resources/images/product/COMPUTER RELATED/T4.JPEG','resources/images/product/COMPUTER RELATED/Inspiron_11_3000_3168_MultiColor.JPEG','1003');



INSERT INTO dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('Inspiron_15_5000_5568_2in1_GDO',20,429.0,'resources/images/product/COMPUTER RELATED/T5.JPEG','resources/images/product/COMPUTER RELATED/Inspiron_15_5000_5568_2in1_GDO.JPEG','1004');


INSERT INTO dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('OPTIPLEX 7440 ALL IN ONE',20,849.99,'resources/images/product/COMPUTER RELATED/T1.JPG','resources/images/product/COMPUTER RELATED/OPTIPLEX 7440 ALL IN ONE.JPG','1005');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('THE REGENERATING SERUM',320,330.99,'resources/images/product/COSMETICS/T11.JPG','resources/images/product/COSMETICS/THE REGENERATING SERUM.JPG','1006');





INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('THE EYE CONCENTRATE',320,219.99,'resources/images/product/COSMETICS/T12.JPG','resources/images/product/COSMETICS/THE EYE CONCENTRATE.JPG','1006');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('CREME DE LA MER',310,319.99,'resources/images/product/COSMETICS/T13.JPG','resources/images/product/COSMETICS/CREME DE LA MER.JPG','10062');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('THE REFINING FACIAL',8310,95.99,'resources/images/product/COSMETICS/T14.JPG','resources/images/product/COSMETICS/THE REFINING FACIAL.JPG','1008');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('THE BODY CREME',3110,275.99,'resources/images/product/COSMETICS/T15.JPG','resources/images/product/COSMETICS/THE BODY CREME.JPG','1000');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('1000 POWER RECHARGEABLE ELECTRIC TOOTHBRUSH',1110,49.99,'resources/images/product/COSMETICS/T1.JPG','resources/images/product/COSMETICS/1000 POWER RECHARGEABLE ELECTRIC TOOTHBRUSH.JPG','10106');

INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('ORAL-B VITALITY FLOSS ACTION RECHARGEABLE ELECTRIC TOOTHBRUSH',1110,26.21,'resources/images/product/COSMETICS/T2.JPG','resources/images/product/COSMETICS/ORAL-B VITALITY FLOSS ACTION RECHARGEABLE ELECTRIC TOOTHBRUSH.JPG','1201');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('Philips Norelco Electric Shaver 2100',1110,29.95,'resources/images/product/COSMETICS/T3.JPG','resources/images/product/COSMETICS/Philips Norelco Electric Shaver 2100.JPG','1436');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('Remington PG6025 All-in-1 Lithium Powered Grooming',1110,17.79,'resources/images/product/COSMETICS/T4.JPG','resources/images/product/COSMETICS/Remington PG6025 All-in-1 Lithium Powered Grooming.JPG','1006');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('BLACK+DECKER EK700 9-Inch Electric Carving Knife, White',1110,13.99,'resources/images/product/COSMETICS/T5.JPG','resources/images/product/COSMETICS/BLACK+DECKER EK700 9-Inch Electric Carving Knife, White.JPG','1009');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE REFLECTIVE JUST DO IT',31110,30.79,'resources/images/product/GARMENTS/T8.JPG','resources/images/product/GARMENTS/NIKE REFLECTIVE JUST DO IT.JPG','11006');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE SPORTSWEAR TECH FLEECE',310,70.79,'resources/images/product/GARMENTS/T6.JPG','resources/images/product/GARMENTS/NIKE SPORTSWEAR TECH FLEECE.JPG','11008');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE SPORTSPANT TECH FLEECE',310,80.79,'resources/images/product/GARMENTS/T9.JPG','resources/images/product/GARMENTS/NIKE SPORTSPANT TECH FLEECE.JPG','11008');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES(' NIKE SPORTWEAR TECH FLEECE AEROLOFT',70,380.79,'resources/images/product/GARMENTS/T7.JPG','resources/images/product/GARMENTS/NIKE SPORTWEAR TECH FLEECE AEROLOFT.JPG','11038');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE THERMA-SPHERE',70,70.79,'resources/images/product/GARMENTS/T7.JPG','resources/images/product/GARMENTS/NIKE THERMA-SPHERE.JPG','1033');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('ADM  Full Size Handcrafted Solid Wood Violin Outfit with Shoulder',90,105.79,'resources/images/product/MUSCIAL INSTRUMENT/T3.JPG','resources/images/product/MUSCIAL INSTRUMENT/ADM  Full Size Handcrafted Solid Wood Violin Outfit with Shoulder.JPG','7033');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('Casio Casio AP250 Celviano 88-Key Digital Piano with Bench',10,1305.79,'resources/images/product/MUSCIAL INSTRUMENT/T5.JPG','resources/images/product/MUSCIAL INSTRUMENT/Casio Casio AP250 Celviano 88-Key Digital Piano with Bench.JPG','7023');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('F.R. Pfretszchner F.R. Pfretszchner 100 Full Size Fully Carved Violin Outfit',10, 699.79,'resources/images/product/MUSCIAL INSTRUMENT/T4.JPG','resources/images/product/MUSCIAL INSTRUMENT/F.R. Pfretszchner F.R. Pfretszchner 100 Full Size Fully Carved Violin Outfit.JPG','7023');




INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES(' Makala Waterman MK-SWTCL Soprano Ukulele- Translucent Clear',110, 49.79,'resources/images/product/MUSCIAL INSTRUMENT/T1.JPG','resources/images/product/MUSCIAL INSTRUMENT/Makala Waterman MK-SWTCL Soprano Ukulele- Translucent Clear.JPG','7025');



INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('Takamine Takamine P1DC Pro Series Dreadnought Acoustic Electric with Hard Case',140, 549.79,'resources/images/product/MUSCIAL INSTRUMENT/T2.JPG','resources/images/product/MUSCIAL INSTRUMENT/Makala Waterman MK-SWTCL Soprano Ukulele- Translucent Clear.JPG','7095');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE LUNAR FORCE 1 DUCKBOOT',2140, 149.79,'resources/images/product/SPORT/T1.JPG','resources/images/product/SPORT/NIKE LUNAR FORCE 1 DUCKBOOT.JPG','9095');


INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE LUNAREPIC LOW FLYKNIT',2120, 180.79,'resources/images/product/SPORT/T3.JPG','resources/images/product/SPORT/NIKE LUNAREPIC LOW FLYKNIT.JPG','9095');




INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE AIR ZOOM STRUCTURE 20',2120, 160.79,'resources/images/product/SPORT/T5.JPG','resources/images/product/SPORT/NIKE AIR ZOOM STRUCTURE 20.JPG','9095');

INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE ROSHE TWO',1120, 90.79,'resources/images/product/SPORT/T2.JPG','resources/images/product/SPORT/NIKE ROSHE TWO.JPG','9097');

INSERT INTO
dbo.product(NAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDOR_ID)
VALUES('NIKE ZOOM LEBRON SOLDIER',1120, 80.79,'resources/images/product/SPORT/T4.JPG','resources/images/product/SPORT/NIKE ZOOM LEBRON SOLDIER.JPG','9097');
