						
INSERT INTO dbo.product (PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES (’Chromebook 11 - 3120’,100,169.0,’COMPUTER RELATED\\T3.JPG’,’COMPUTER RELATED\\Chromebook 11 - 3120.JPG’,’1001’);



INSERT INTO dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’INSPIRON SMALL DESKTOP’,20,279.0,’COMPUTER RELATED\\T2.JPG’,’COMPUTER RELATED\\INSPIRON SMALL DESKTOP.JPG’,’1002’);



INSERT INTO dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’Inspiron_11_3000_3168_MultiColor’,120,199.0,’COMPUTER RELATED\\T4.JPEG’,’COMPUTER RELATED\\Inspiron_11_3000_3168_MultiColor.JPEG’,’1003’);



INSERT INTO dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’Inspiron_15_5000_5568_2in1_GDO’,20,429.0,’COMPUTER RELATED\\T5.JPEG’,’COMPUTER RELATED\\Inspiron_15_5000_5568_2in1_GDO.JPEG’,’1004’);


INSERT INTO dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’’OPTIPLEX 7440 ALL IN ONE’,20,849.99,’COMPUTER RELATED\\T1.JPG’,’COMPUTER RELATED\\OPTIPLEX 7440 ALL IN ONE.JPG’,’1005’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’’THE REGENERATING SERUM’,320,330.99,’COSMETICS\\T11.JPG’,’COSMETICS\\THE REGENERATING SERUM.JPG’,’1006’);





INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’’THE EYE CONCENTRATE’,320,219.99,’COSMETICS\\T12.JPG’,’COSMETICS\\THE EYE CONCENTRATE.JPG’,’1006’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’CREME DE LA MER’,310,319.99,’COSMETICS\\T13.JPG’,’COSMETICS\\CREME DE LA MER.JPG’,’10062’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’THE REFINING FACIAL’,8310,95.99,’COSMETICS\\T14.JPG’,’COSMETICS\\THE REFINING FACIAL.JPG’,’1008’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’THE BODY CREME’,3110,275.99,’COSMETICS\\T15.JPG’,’COSMETICS\\THE BODY CREME.JPG’,’1000’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’1000 POWER RECHARGEABLE ELECTRIC TOOTHBRUSH’,1110,49.99,’COSMETICS\\T1.JPG’,’COSMETICS\\1000 POWER RECHARGEABLE ELECTRIC TOOTHBRUSH.JPG’,’10106’);

INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’ORAL-B VITALITY FLOSS ACTION RECHARGEABLE ELECTRIC TOOTHBRUSH’,1110,26.21,’COSMETICS\\T2.JPG’,’COSMETICS\\ORAL-B VITALITY FLOSS ACTION RECHARGEABLE ELECTRIC TOOTHBRUSH.JPG’,’1201’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’Philips Norelco Electric Shaver 2100’,1110,29.95,’COSMETICS\\T3.JPG’,’COSMETICS\\Philips Norelco Electric Shaver 2100.JPG’,’1436’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’Remington PG6025 All-in-1 Lithium Powered Grooming’,1110,17.79,’COSMETICS\\T4.JPG’,’COSMETICS\\Remington PG6025 All-in-1 Lithium Powered Grooming.JPG’,’1006’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’BLACK+DECKER EK700 9-Inch Electric Carving Knife, White’,1110,13.99,’COSMETICS\\T5.JPG’,’COSMETICS\\BLACK+DECKER EK700 9-Inch Electric Carving Knife, White.JPG’,’1009’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE REFLECTIVE JUST DO IT’,31110,30.79,’GARMENTS\\T8.JPG’,’GARMENTS\\NIKE REFLECTIVE JUST DO IT.JPG’,’11006’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE SPORTSWEAR TECH FLEECE’,310,70.79,’GARMENTS\\T6.JPG’,’GARMENTS\\NIKE SPORTSWEAR TECH FLEECE.JPG’,’11008’);


INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE SPORTSPANT TECH FLEECE’,310,80.79,’GARMENTS\\T9.JPG’,’GARMENTS\\NIKE SPORTSPANT TECH FLEECE.JPG’,’11008’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’ NIKE SPORTWEAR TECH FLEECE AEROLOFT’,70,380.79,’GARMENTS\\T7.JPG’,’GARMENTS\\NIKE SPORTWEAR TECH FLEECE AEROLOFT.JPG’,’11038’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE THERMA-SPHERE’,70,70.79,’GARMENTS\\T7.JPG’,’GARMENTS\\NIKE THERMA-SPHERE.JPG’,’1033’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’ADM  Full Size Handcrafted Solid Wood Violin Outfit with Shoulder’,90,105.79,’MUSCIAL INSTRUMENT\\T3.JPG’,’MUSCIAL INSTRUMENT\\ADM  Full Size Handcrafted Solid Wood Violin Outfit with Shoulder.JPG’,’7033’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’Casio Casio AP250 Celviano 88-Key Digital Piano with Bench’,10,1305.79,’MUSCIAL INSTRUMENT\\T5.JPG’,’MUSCIAL INSTRUMENT\\Casio Casio AP250 Celviano 88-Key Digital Piano with Bench.JPG’,’7023’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’F.R. Pfretszchner F.R. Pfretszchner 100 Full Size Fully Carved Violin Outfit’,10, 699.79,’MUSCIAL INSTRUMENT\\T4.JPG’,’MUSCIAL INSTRUMENT\\F.R. Pfretszchner F.R. Pfretszchner 100 Full Size Fully Carved Violin Outfit.JPG’,’7023’);




INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’ Makala Waterman MK-SWTCL Soprano Ukulele- Translucent Clear’,110, 49.79,’MUSCIAL INSTRUMENT\\T1.JPG’,’MUSCIAL INSTRUMENT\\Makala Waterman MK-SWTCL Soprano Ukulele- Translucent Clear.JPG’,’7025’);



INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’Takamine Takamine P1DC Pro Series Dreadnought Acoustic Electric with Hard Case’,140, 549.79,’MUSCIAL INSTRUMENT\\T2.JPG’,’MUSCIAL INSTRUMENT\\Makala Waterman MK-SWTCL Soprano Ukulele- Translucent Clear.JPG’,’7095’);




INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE LUNAR FORCE 1 DUCKBOOT’,2140, 149.79,’SPORT\\T1.JPG’,’SPORT\\NIKE LUNAR FORCE 1 DUCKBOOT.JPG’,’9095’);




INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE LUNAREPIC LOW FLYKNIT’,2120, 180.79,’SPORT\\T3.JPG’,’SPORT\\NIKE LUNAREPIC LOW FLYKNIT.JPG’,’9095’);




INSERT INTO
dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE AIR ZOOM STRUCTURE 20’,2120, 160.79,’SPORT\\T5.JPG’,’SPORT\\NIKE AIR ZOOM STRUCTURE 20.JPG’,’9095’);

dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE ROSHE TWO’,1120, 90.79,’SPORT\\T2.JPG’,’SPORT\\NIKE ROSHE TWO.JPG’,’9097’);


dbo.product(PRODUCTNAME,QUANTITY,PRICE,THUMBNAIL,IMAGE,VENDORID)
VALUES(’NIKE ZOOM LEBRON SOLDIER’,1120, 80.79,’SPORT\\T4.JPG’,’SPORT\\NIKE ZOOM LEBRON SOLDIER.JPG’,’9097’);